### ISSUE TITLE
Problém konverze měny na https://www.ikea.com/cz/cs/p/vimle-5m-rohova-rozkl-pohovka-s-lenoskou-grann-bomstad-cerna-s79477377/

### ISSUE THREAD

**Issue by M4ndarrr** [jonasjancarik/ikea-price-scout#1]
Summary:
Cena není převedena z lokální měn na CZK.

Steps to Reproduce: 
Tento odkaz
https://www.ikea.com/cz/cs/p/vimle-5m-rohova-rozkl-pohovka-s-lenoskou-grann-bomstad-cerna-s79477377/

Screenshots:

![image](https://github.com/user-attachments/assets/0698c039-3495-47f4-90ac-4efea202e0d3)

**Comment by jonasjancarik** [comment]
Pořád je problém s konverzí velkých částek v německém/rakouském formátu
