### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: chrome-extension://oopdjcbknccainhnahjcpnanigggmgmm/main.js

### ISSUE THREAD

**Issue by sutomas1984** [jonasjancarik/ikea-price-scout#2]
Rozšíření vypisuje tuto  chybu na jakekoli produktové stránce po instalaci. 

content-script.js:19 (anonymní funkce)

// content-script.js

(async () => {
    const moduleUrls = {
        main: chrome.runtime.getURL('main.js'),
        ProductPage: chrome.runtime.getURL('pages/ProductPage.js'),
        CartPage: chrome.runtime.getURL('pages/CartPage.js'),
        Cart: chrome.runtime.getURL('models/Cart.js'),
        ProductItem: chrome.runtime.getURL('models/ProductItem.js'),
        ExchangeRates: chrome.runtime.getURL('utils/ExchangeRates.js'),
        DisplayUtils: chrome.runtime.getURL('utils/DisplayUtils.js'),
        DomUtils: chrome.runtime.getURL('utils/DomUtils.js'),
        PriceUtils: chrome.runtime.getURL('utils/PriceUtils.js'),
        ErrorUtils: chrome.runtime.getURL('utils/ErrorUtils.js'),
    };

    const main = await import(moduleUrls.main);
    main.default(moduleUrls);
})();

**Comment by jonasjancarik** [comment]
Myslím, že tohle už jsem odchytil (https://github.com/jonasjancarik/ikea-price-scout/commit/19a136dac2ab945c2e0ad75d05457ca4ef9a7c8d). Vypadlo mi z manifestu web_accessible_resources. Můžu poprosit o potvrzení, že teď už to funguje? Případně zkuste nainstalovat znova rozšíření ze store, ale mělo by se snad aktualizovat samo. Díky

**Comment by sutomas1984** [comment]
Zdravím a potvrzuji, nyní bez problémů, vše funkční. Díky
